default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: base_team_project_82_development

test:
  <<: *default
  database: base_team_project_82_test

production:
  <<: *default
  database: base_team_project_production
  username: base_team_project
  password: <%= ENV['BASE_TEAM_PROJECT_DATABASE_PASSWORD'] %>
